[package]
name = "easyreg-server"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "easyreg-server"
path = "src/main.rs"

[dependencies]
axum.workspace = true
easyreg-core = { path = "../../crates/easyreg-core" }
easyreg-engine = { path = "../../crates/easyreg-engine" }
easyreg-semantics = { path = "../../crates/easyreg-semantics" }
serde.workspace = true
tokio.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
