[package]
name = "easyreg-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
easyreg-core = { path = "../easyreg-core" }
easyreg-dialects = { path = "../easyreg-dialects" }
easyreg-inference = { path = "../easyreg-inference" }
easyreg-validation = { path = "../easyreg-validation" }
thiserror.workspace = true

[lints]
workspace = true
