[package]
name = "easyreg-inference"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
easyreg-core = { path = "../easyreg-core" }
easyreg-detectors = { path = "../easyreg-detectors" }
thiserror.workspace = true

[lints]
workspace = true
